### ISSUE TITLE
wifi370 led controller

### ISSUE THREAD

**Issue by RSMBS** [firsttris/homebridge-wifi370-led-controller#2]
ich have the 730led controller which you linked on amazon, it got an ip dress but HomeKit won't find it...what should I type in as controller type? this one isn't mentions in the table down...

**Comment by firsttris** [comment]
i think mine was a LW12, but the amazon link could have changed in the meantime, can't say for sure

**Comment by RSMBS** [comment]
ok thanks for the answer in the first way.
but it still doesn't function.
i will restarg my router and the controller again and try some things.

**Comment by firsttris** [comment]
first try the mobile app from the controller

**Comment by RSMBS** [comment]
yes that works over wifi but sadly not over homebridge
